-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2026-04-23 15:13:09 CST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

create table TBL_ABONADOS (
   CODIGO_ABONADO number not null
);

alter table TBL_ABONADOS add constraint TBL_ABONADOS_PK primary key ( CODIGO_ABONADO );

create table TBL_CUENTAS (
   CODIGO_CUENTA  number not null,
   CODIGO_PEGUE   number not null,
   CODIGO_MES     number not null,
   CODIGO_ESTADO  number not null,
   MONTO_ESPERADO number
);

alter table TBL_CUENTAS add constraint TBL_CUENTAS_PK primary key ( CODIGO_CUENTA );

create table TBL_DETALLE_PAGOS (
   CODIGO_DETALLE number not null,
   CODIGO_CUENTA  number not null,
   CODIGO_PAGO    number not null,
   DESCRIPCION    varchar2(200)
);

alter table TBL_DETALLE_PAGOS add constraint TBL_DETALLE_PAGOS_PK primary key ( CODIGO_DETALLE );

create table TBL_ENCARGADOS (
   CODIGO_ENCARGADO number not null,
   NUMERO_ENCARGADO number not null
);

alter table TBL_ENCARGADOS add constraint TBL_ENCARGADOS_PK primary key ( CODIGO_ENCARGADO );

alter table TBL_ENCARGADOS add constraint TBL_ENCARGADOS__UN unique ( NUMERO_ENCARGADO );

create table TBL_ESTADO_CUENTAS (
   CODIGO_ESTADO number not null,
   NOMBRE        varchar2(100) not null,
   DESCRIPCION   varchar2(100)
);

alter table TBL_ESTADO_CUENTAS add constraint TBL_ESTADO_CUENTAS_PK primary key ( CODIGO_ESTADO );

create table TBL_ESTADO_PEGUES (
   CODIGO_ESTADO number not null,
   NOMBRE        varchar2(50)
);

alter table TBL_ESTADO_PEGUES add constraint TBL_ESTADO_PEGUES_PK primary key ( CODIGO_ESTADO );

create table TBL_MES (
   CODIGO_MES number not null,
   NOMBRE     varchar2(100) not null,
   ANIO       number not null
);

alter table TBL_MES add constraint TBL_MENSUALIDADES_PK primary key ( CODIGO_MES );

create table TBL_PAGOS (
   CODIGO_PAGO         number not null,
   CODIGO_ENCARGADO    number not null,
   CODIGO_PERSONA_PAGA number,
   CODIGO_TIPO_PAGO    number not null,
   FECHA_PAGO          date not null,
   MONTO               number not null
);

alter table TBL_PAGOS add constraint TBL_PAGOS_PK primary key ( CODIGO_PAGO );

create table TBL_PEGUES (
   CODIGO_PEGUE   number not null,
   CODIGO_ESTADO  number not null,
   CODIGO_ABONADO number not null,
   CODIGO_TARIFA  number not null,
   COSTO_PEGUE    number
);

alter table TBL_PEGUES add constraint TBL_PEGUES_PK primary key ( CODIGO_PEGUE );

create table TBL_PERSONAS (
   CODIGO_PERSONA   number not null,
   NOMBRE           varchar2(100) not null,
   APELLIDO         varchar2(100) not null,
   NUMERO_IDENTIDAD varchar2(20) not null,
   TELEFONO         varchar2(50),
   CORREO           varchar2(100)
);

alter table TBL_PERSONAS add constraint TBL_PERSONAS_PK primary key ( CODIGO_PERSONA );

alter table TBL_PERSONAS add constraint TBL_PERSONAS__UN unique ( NUMERO_IDENTIDAD,
                                                                  CORREO );

create table TBL_TARIFAS (
   CODIGO_TARIFA number not null,
   DESCRIPCION   varchar2(500),
   COSTO         number
);

alter table TBL_TARIFAS add constraint TBL_TARIFAS_PK primary key ( CODIGO_TARIFA );

create table TBL_TIPO_PAGOS (
   CODIGO_TIPO_PAGO number not null,
   NOMBRE           varchar2(50) not null
);

alter table TBL_TIPO_PAGOS add constraint TBL_TIPO_PAGOS_PK primary key ( CODIGO_TIPO_PAGO );

alter table TBL_CUENTAS
   add constraint CUENTAS_ESTADO_CUENTAS_FK foreign key ( CODIGO_ESTADO )
      references TBL_ESTADO_CUENTAS ( CODIGO_ESTADO );

alter table TBL_CUENTAS
   add constraint CUENTAS_MES_FK foreign key ( CODIGO_MES )
      references TBL_MES ( CODIGO_MES );

alter table TBL_CUENTAS
   add constraint CUENTAS_PEGUES_FK foreign key ( CODIGO_PEGUE )
      references TBL_PEGUES ( CODIGO_PEGUE );

alter table TBL_DETALLE_PAGOS
   add constraint DETALLE_PAGOS_CUENTAS_FK foreign key ( CODIGO_CUENTA )
      references TBL_CUENTAS ( CODIGO_CUENTA );

alter table TBL_DETALLE_PAGOS
   add constraint DETALLE_PAGOS_PAGOS_FK foreign key ( CODIGO_PAGO )
      references TBL_PAGOS ( CODIGO_PAGO );

alter table TBL_PAGOS
   add constraint PAGOS_ENCARGADOS_FK foreign key ( CODIGO_ENCARGADO )
      references TBL_ENCARGADOS ( CODIGO_ENCARGADO );

alter table TBL_PAGOS
   add constraint PAGOS_PERSONAS_FK foreign key ( CODIGO_PERSONA_PAGA )
      references TBL_PERSONAS ( CODIGO_PERSONA );

alter table TBL_PAGOS
   add constraint PAGOS_TIPO_PAGOS_FK foreign key ( CODIGO_TIPO_PAGO )
      references TBL_TIPO_PAGOS ( CODIGO_TIPO_PAGO );

alter table TBL_PEGUES
   add constraint PEGUES_ABONADOS_FK foreign key ( CODIGO_ABONADO )
      references TBL_ABONADOS ( CODIGO_ABONADO );

alter table TBL_PEGUES
   add constraint PEGUES_ESTADO_PEGUES_FK foreign key ( CODIGO_ESTADO )
      references TBL_ESTADO_PEGUES ( CODIGO_ESTADO );

alter table TBL_PEGUES
   add constraint PEGUES_TARIFAS_FK foreign key ( CODIGO_TARIFA )
      references TBL_TARIFAS ( CODIGO_TARIFA );

alter table TBL_ABONADOS
   add constraint TBL_ABONADOS_TBL_PERSONAS_FK foreign key ( CODIGO_ABONADO )
      references TBL_PERSONAS ( CODIGO_PERSONA );

alter table TBL_ENCARGADOS
   add constraint TBL_ENCARGADOS_TBL_PERSONAS_FK foreign key ( CODIGO_ENCARGADO )
      references TBL_PERSONAS ( CODIGO_PERSONA );

alter table TBL_PEGUES add (
   UBICACION varchar2(100)
);

alter table TBL_PEGUES add (
   FECHA_INSTALACION date
)

alter table TBL_PEGUES add CODIGO_CASA varchar2(50);

alter table TBL_PEGUES add constraint TBL_PEGUES_CASAS_U unique ( CODIGO_CASA );


alter table TBL_PERSONAS modify (
   NUMERO_IDENTIDAD NULL
);


alter table TBL_DETALLE_PAGOS add constraint UQ_PAGO_UNICO_POR_MES unique ( CODIGO_CUENTA );


alter table TBL_CUENTAS add constraint UQ_PEGUE_MES unique ( CODIGO_PEGUE,
                                                             CODIGO_MES );

alter table TBL_PAGOS add MOTIVO_MODIFICACION varchar2(250);


-- Creas la secuencia con un nombre claro
create sequence SEQ_CODIGO_PERSONA start with 1 increment by 1 nocache nocycle;


create sequence SEQ_NUMERO_ENCARGADO start with 1 increment by 1 nocache nocycle;


create sequence SEQ_CODIGO_PEGUE start with 1 increment by 1 nocache nocycle;

create sequence SEQ_CODIGO_CUENTA start with 1 increment by 1 nocache nocycle;

create sequence SEQ_CODIGO_DETALLE start with 1 increment by 1 nocache nocycle;

create sequence SEQ_CODIGO_PAGO start with 1 increment by 1 nocache nocycle;













-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0